name: _GNRankup
main: garusnetwork.rankup.Main
author: Megadix
version: 1.1
description: Plugin de rankup para o Garus Network
commands:
    rankup:
        description: Comando para evoluir rank
    ranks:
        description: Comando para listar os Ranks